name: Example Workflow
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job1:
    uses: singaraju9441/Ansible/.github/workflows/demo.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: echo "Building the project..."
